# Generated by Django 4.2.18 on 2025-03-06 04:20

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app.models.ScimUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='scim_id',
            field=models.CharField(
                blank=True,
                default=None,
                help_text='A unique identifier for a SCIM resource as defined by the service provider.',
                max_length=254,
                null=True,
                unique=True,
                verbose_name='SCIM ID',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='scim_id',
            field=models.CharField(
                blank=True,
                default=None,
                help_text='A unique identifier for a SCIM resource as defined by the service provider.',
                max_length=254,
                null=True,
                unique=True,
                verbose_name='SCIM ID',
            ),
        ),
    ]
